spring:
  datasource:
    url: jdbc:mysql://192.168.116.128:3307
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Order
  rabbitmq:
    port: 5762
    host: 192.168.116.129
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
