spring:
  datasource:
    url: jdbc:mysql://192.168.116.129:3307/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  application:
    name: Order
  rabbitmq:
    port: 5672
    host: 192.168.116.129
    username: root
    password: 123456
server:
  port: 8081
