env: dev1
spring:
  rabbitmq:
    port: 5672
    username: root
    password: 123456
    host: 192.168.116.128
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.116.128:3307/test
    username: root
    password: 123456
server:
  port: 8083
phong:
  name: phong
  age: 22
