spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    port: 5762
    host: localhost
    username: guest
    password: guest
server:
  port: 8082
